inicio/urls.py
from django.urls import path
from inicio import views

app_name = "inicio"

urlpatterns = [
    path('', views.menu, name ='inicio'),
    
    path('sobre-mi/', views.sobre_mi, name='sobre_mi'),
    
    path("Articulos/<int:pk>/", views.MostrarArticulo.as_view(), name ="mostrar_articulos"),
     
    path("Articulos/Lista/", views.ListaArticulos.as_view(), name ="listar_articulos"),
    path("Articulos/", views.CrearArticulos.as_view(), name ="Articulos"),
    path("Articulos/<int:pk>/Modificar/", views.ModificarArticulos.as_view() , name ="modificar_articulos"), 
    path("Articulos/<int:pk>/Eliminar/", views.EliminarArticulos.as_view() , name ="eliminar_articulos"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("inicio/", include("inicio.urls")),
    path("usuarios/", include("usuarios.urls")),
    path('admin/', admin.site.urls), 
    ]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

inicio/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Articulo(models.Model):
    nombre = models.CharField(max_length=20)
    color = models.CharField(max_length=20)
    version = RichTextField()
    marca = models.CharField(max_length=20)
    cantidad_requerida = models.IntegerField(null=True)
    imagen = models.ImageField(upload_to='articulos', null=True, blank=True)
   
    
    def __str__(self):
        return f"{self.nombre}, {self.marca}"
    
    

inicio/forms.py
from django import forms

class CreacionArticuloFormulario(forms.Form):
    nombre = forms.CharField(max_length=20)
    color = forms.CharField(max_length=20)
    version = forms.CharField(max_length=20)
    marca = forms.CharField(max_length=20)
    cantidad_requerida = forms.IntegerField(required=False)
    imagen= forms.ImageField(required=False)
    
class ModificarArticuloFormulario(forms.Form):
    nombre = forms.CharField(max_length=20)
    color = forms.CharField(max_length=20)
    version = forms.CharField(max_length=20)
    marca = forms.CharField(max_length=20)   
    cantidad_requerida = forms.IntegerField(required=False)
    imagen= forms.ImageField(required=False)
    
class BuscarArticulo(forms.Form):
    nombre = forms.CharField(max_length=20)

inicio/views.py
from inicio.models import Articulo
from django.shortcuts import render

from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

def menu(request):
    return render(request, "inicio/menu.html")

def sobre_mi(request):
    return render(request, 'inicio/sobre_mi.html')
    

class ListaArticulos(ListView):
    model = Articulo
    template_name = "inicio/CBV/lista_articulos.html"
    
class CrearArticulos(LoginRequiredMixin,CreateView):
    model = Articulo
    template_name = "inicio/CBV/crear_articulos.html"
    success_url = reverse_lazy("inicio:listar_articulos")
    fields = ["nombre", "color", "version", "marca", "imagen"]
    
class ModificarArticulos(LoginRequiredMixin,UpdateView):
    model = Articulo
    template_name = "inicio/CBV/modificar_articulos.html"
    success_url = reverse_lazy("inicio:listar_articulos")
    fields = ["nombre", "color", "version", "marca", "cantidad_requerida", "imagen"]
    
class EliminarArticulos(LoginRequiredMixin,DeleteView):
    model = Articulo
    template_name = "inicio/CBV/eliminar_articulos.html"
    success_url = reverse_lazy("inicio:listar_articulos")
    
class MostrarArticulo(DetailView):
    model = Articulo
    template_name = "inicio/CBV/mostrar_articulos.html"

inicio/templates/inicio/CBV/crear_articulos.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Articulos</title>
{% endblock title_head %}

{% block h1_header  %}
<h1> Comprar Articulos </h1>
{% endblock h1_header %}

{% block contenido %}

<form action={% url 'inicio:Articulos' %} method="POST" enctype="multipart/form-data">
   {% csrf_token %}
   <table>
      {{form.media}}
      {{form}}
   </table>
   <button>Crear</button>    
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/eliminar_articulos.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Eliminar Articulos</title>
{% endblock title_head %}

{% block h1_header  %}
<h1> Eliminar Articulos </h1>
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'inicio:eliminar_articulos' articulo.id %} method="POST">
   {% csrf_token %}
   <p>Desea realmente eliminar a articulo {{articulo}}</p>
   <button>Eliminar</button>    
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/lista_articulos.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Articulos</title>
{% endblock title_head %}

{% block h1_header  %}
<h1> Mostrar Articulos </h1>
{% endblock h1_header %}

{% block contenido %}

{% if object_list %}
<ul>
    {% for articulo in object_list %}
    <li><a href={% url 'inicio:mostrar_articulos' articulo.id %}>{{articulo}}</a></li>
    <a href={% url 'inicio:modificar_articulos' articulo.id %}>Modificar</a> . <a href={% url 'inicio:eliminar_articulos' articulo.id %}>Eliminar</a>
    {% endfor %}
</ul>

 {% else %}
      <h2>No hay articulos seleccionados</h2>
 {% endif %}

 
{% endblock contenido %}

inicio/templates/inicio/CBV/modificar_articulos.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Modificar Articulos</title>
{% endblock title_head %}

{% block h1_header  %}
<h1> Modificar Articulos </h1>
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'inicio:modificar_articulos' articulo.id %} method="POST" enctype="multipart/form-data">
   {% csrf_token %}
   <table>
   {{form.media}}
   {{form}}
   </table>
   <button>Modificar</button>    
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/mostrar_articulos.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Articulos</title>
{% endblock title_head %}

{% block h1_header  %}
<h1> {{articulo}} </h1>
{% endblock h1_header %}

{% block contenido %}
<ul>
    <li>Nombre : {{articulo.nombre}}</li>
    <li>Color : {{articulo.color}}</li>
    <li>Version : {{articulo.version  | safe}}</li>
    <li>Marca : {{articulo.marca}}</li>
    <li>Cantidad Requerida : {{articulo.cantidad_requerida}}</li>
    {% if articulo.imagen and articulo.imagen.url %}
    <img src="{{ articulo.imagen.url }}" alt="" height="120px">
    {% else %}
    <p>No hay imagen seleccionada</p>
    {% endif %}
    
</ul>

{% endblock contenido %}