inicio/urls.py
from django.urls import path
from inicio import views

app_name = "inicio"

urlpatterns = [
    path('', views.menu, name ='inicio'),
    
    path('sobre-mi/', views.sobre_mi, name='sobre_mi'),
    
    path("Articulos/<int:pk>/", views.MostrarArticulo.as_view(), name ="mostrar_articulos"),
     
    path("Articulos/Lista/", views.ListaArticulos.as_view(), name ="listar_articulos"),
    path("Articulos/", views.CrearArticulos.as_view(), name ="Articulos"),
    path("Articulos/<int:pk>/Modificar/", views.ModificarArticulos.as_view() , name ="modificar_articulos"), 
    path("Articulos/<int:pk>/Eliminar/", views.EliminarArticulos.as_view() , name ="eliminar_articulos"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("inicio/", include("inicio.urls")),
    path("usuarios/", include("usuarios.urls")),
    path('admin/', admin.site.urls), 
    ]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path 
from usuarios import views
from django.contrib.auth.views import LogoutView

app_name= "usuarios"
 
urlpatterns =[
    path("login/", views.login, name = "login"),
    path("registro/", views.registro, name = "registro"),
    path("editar-perfil/", views.editar_perfil, name = "editar_perfil"),
    path("logout/", LogoutView.as_view(template_name="usuarios/logout.html"), name = "logout"),
    path("cambio-contrasenia/", views.CambioContrasenia.as_view() , name = "cambio_contrasenia"),
    path("datos-perfil/", views.datos_perfil, name = "datos_perfil"),
]    

templates/genericos/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Inicio</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "inicio/css/styles.css" %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'inicio:inicio' %}">Menu</a>
                <a class="navbar-brand" href="{% url 'inicio:Articulos' %}">Crear Articulos</a>
                <a class="navbar-brand" href="{% url 'inicio:listar_articulos' %}">Articulos</a>
                {% if request.user.is_authenticated %}
                {% if request.user.informacionextra.avatar %}
                <img src={{request.user.informacionextra.avatar.url}} alt="" height="40px">
                {% endif %}
                
                <a class="navbar-brand" href={% url 'usuarios:datos_perfil' %}>Datos Perfil</a>
                <a class="btn btn-primary" href={% url 'usuarios:logout' %}>Cerrar Sesion</a>

                {% else %}
                
                    <a class="btn btn-primary" href={% url 'usuarios:login' %}>Iniciar Sesion</a>
                    <a class="btn btn-primary" href={% url 'usuarios:registro' %}>Registrarse</a>

                {% endif %}
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            {% block h1_header  %}
                            <h1 class="mb-5">Bienvenido a la pagina web del proyecto CoderHouse!</h1>
                            {% endblock h1_header %}
                            
                            <!-- Signup form-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                        
                                <!-- Email address input-->
                                
                                <!-- Submit error message-->
                                <!---->
                                <!-- This is what your users will see when there is-->
                                <!-- an error submitting the form-->
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% block contenido %}
        {% endblock contenido %}
                            
        <!-- Icons Grid-->
        <!-- Image Showcases-->
        <!-- Testimonials-->
        <!-- Call to Action-->
     
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href={% url 'inicio:sobre_mi' %}>Sobre Mi</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "inicio/js/scripts.js"%}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>