inicio/urls.py
from django.urls import path
from inicio import views

app_name = "inicio"

urlpatterns = [
    path('', views.menu, name ='inicio'),
    
    path('sobre-mi/', views.sobre_mi, name='sobre_mi'),
    
    path("Articulos/<int:pk>/", views.MostrarArticulo.as_view(), name ="mostrar_articulos"),
     
    path("Articulos/Lista/", views.ListaArticulos.as_view(), name ="listar_articulos"),
    path("Articulos/", views.CrearArticulos.as_view(), name ="Articulos"),
    path("Articulos/<int:pk>/Modificar/", views.ModificarArticulos.as_view() , name ="modificar_articulos"), 
    path("Articulos/<int:pk>/Eliminar/", views.EliminarArticulos.as_view() , name ="eliminar_articulos"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("inicio/", include("inicio.urls")),
    path("usuarios/", include("usuarios.urls")),
    path('admin/', admin.site.urls), 
    ]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path 
from usuarios import views
from django.contrib.auth.views import LogoutView

app_name= "usuarios"
 
urlpatterns =[
    path("login/", views.login, name = "login"),
    path("registro/", views.registro, name = "registro"),
    path("editar-perfil/", views.editar_perfil, name = "editar_perfil"),
    path("logout/", LogoutView.as_view(template_name="usuarios/logout.html"), name = "logout"),
    path("cambio-contrasenia/", views.CambioContrasenia.as_view() , name = "cambio_contrasenia"),
    path("datos-perfil/", views.datos_perfil, name = "datos_perfil"),
]    

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class InformacionExtra(models.Model):
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)
    city = models.CharField(max_length=20, null = True, blank = True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    

    

usuarios/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

class MiFormularioDeCreacion(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label = "Contraseña", widget = forms.PasswordInput)
    password2 = forms.CharField(label = "Repetir Contraseña", widget = forms.PasswordInput)

    
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2",]
        help_texts = {k: "" for k in fields}
        
        

class EdicionDatosUsuario(UserChangeForm):
    password = None 
    email = forms.EmailField()
    first_name = forms.CharField(label="Nombre", max_length=20)
    last_name = forms.CharField(label="Apellido", max_length=20)
    city = forms.CharField(label="Ciudad", max_length=20)
    
    avatar= forms.ImageField(required=False)
    
    class Meta:
         model = User
         fields = ["email", "first_name", "last_name", "avatar", "city"]
         
        

usuarios/views.py
from django.shortcuts import render
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import PasswordChangeView

from django.contrib.auth import authenticate, login as django_login
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from usuarios.models import InformacionExtra
from usuarios.forms import MiFormularioDeCreacion, EdicionDatosUsuario

# Create your views here.

def login(request):
    
    
    if request.method == "POST":
        formulario = AuthenticationForm(request, data=request.POST)
        
        if formulario.is_valid():
            nombre_usuario = formulario.cleaned_data.get("username")
            contrasenia = formulario.cleaned_data.get("password")
            usuario = authenticate(username=nombre_usuario, password=contrasenia)
            django_login(request, usuario)
            InformacionExtra.objects.get_or_create(user=request.user)
            return redirect("inicio:inicio")
        else: 
            return render(request, "usuarios/login.html", {"formulario": formulario})
        

        
    formulario = AuthenticationForm()
    return render(request, "usuarios/login.html", {"formulario": formulario})


def registro(request):
    
    if request.method == "POST":
        formulario = MiFormularioDeCreacion(request.POST)
         
        if formulario.is_valid():
            formulario.save()
            return redirect("usuarios:login")
        else:
            return render(request, "usuarios/registro.html", {"formulario": formulario})
     
    formulario = MiFormularioDeCreacion()
    return render(request, "usuarios/registro.html", {"formulario": formulario})

@login_required       
def editar_perfil(request):
    
    if request.method == "POST":
        formulario = EdicionDatosUsuario(request.POST, request.FILES , instance=request.user)
         
        if formulario.is_valid():
            if formulario.cleaned_data.get('avatar'):
                request.user.informacionextra.avatar = formulario.cleaned_data.get("avatar")
            if formulario.cleaned_data.get('city'):
                request.user.informacionextra.city = formulario.cleaned_data.get("city")
            request.user.informacionextra.save()
            formulario.save()
            return redirect("inicio:inicio")
        else:
            return render(request, "usuarios/editar_perfil.html", {"formulario": formulario})
     
    formulario = EdicionDatosUsuario(initial={'avatar': request.user.informacionextra.avatar, 'city': request.user.informacionextra.city}, instance=request.user)
    return render(request, "usuarios/editar_perfil.html", {"formulario": formulario})

    
class CambioContrasenia(PasswordChangeView):
    template_name = 'usuarios/cambiar_contrasenia.html'
    success_url = reverse_lazy('usuarios:editar_perfil')
    
    
@login_required       
def datos_perfil(request):
    
    if request.method == "POST":
        formulario = EdicionDatosUsuario(request.POST, request.FILES , instance=request.user)
         
        if formulario.is_valid():
            if formulario.cleaned_data.get('avatar'):
                request.user.informacionextra.avatar = formulario.cleaned_data.get("avatar")
            if formulario.cleaned_data.get('city'):
                request.user.informacionextra.city = formulario.cleaned_data.get("city")
            request.user.informacionextra.save()
            formulario.save()
            return redirect("inicio:inicio")
        else:
            return render(request, "usuarios/datos_perfil.html", {"formulario": formulario})
     
    formulario = EdicionDatosUsuario(initial={'avatar': request.user.informacionextra.avatar, 'city': request.user.informacionextra.city}, instance=request.user)
    return render(request, "usuarios/datos_perfil.html", {"formulario": formulario})

usuarios/templates/usuarios/cambiar_contrasenia.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Cambio Contrasenia</title>
{% endblock title_head %}

{% block h1_header  %}
<h1 class="mb-5"> Cambio Contrasenia</h1>
{% endblock h1_header %}

{% block contenido %}

{% if form.errors %}
<p style="color: red">Hay errores</p>
{% endif %}

<form action={% url 'usuarios:cambio_contrasenia' %} method="post">
    {% csrf_token %}
    <table>
    {{form}}
    </table>
    <button> Cambiar </button>
</form>
{% endblock contenido %}

usuarios/templates/usuarios/datos_perfil.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Datos Perfil</title>
{% endblock title_head %}

{% block h1_header  %}
<h1 class="mb-5"> Datos Perfil</h1>
{% endblock h1_header %}

{% block contenido %}

<ul>
    <li>Email : {{user.email}}</li>
    <li>Nombre : {{user.first_name}}</li>
    <li>Apellido : {{user.last_name}}</li>
    <li>Avatar : <img src={{request.user.informacionextra.avatar.url}} alt="" height="40px"></li>
    <li>Ciudad : {{user.informacionextra.city}}</li>
   
    
</ul>
    <a href={% url 'usuarios:editar_perfil' %}>{{request.user.username}} </a> <p>Editar Perfil</p>
    
{% endblock contenido %}

usuarios/templates/usuarios/editar_perfil.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Editar Perfil</title>
{% endblock title_head %}

{% block h1_header  %}
<h1 class="mb-5"> Editar Perfil</h1>
{% endblock h1_header %}

{% block contenido %}

{% if formulario.errors %}
<p style="color: red">Hay errores</p>
{% endif %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{formulario}}
    </table>
    <button type="button"><a class="navbar-brand" href={% url 'usuarios:cambio_contrasenia' %}> Cambiar Contrasenia </a> </button>
    <button> Guardar Cambios </button>
</form>
{% endblock contenido %}

usuarios/templates/usuarios/login.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Inicio De Sesion</title>
{% endblock title_head %}

{% block h1_header  %}
<h1 class="mb-5"> Inicio De Sesion</h1>
{% endblock h1_header %}

{% block contenido %}

{% if formulario.errors %}
<p style="color: red">Hay errores</p>
{% endif %}

<form action={% url 'usuarios:login' %} method="post">
    {% csrf_token %}
    <table>
    {{formulario}}
    </table>
    <button> Iniciar Sesion</button>
</form>
{% endblock contenido %}

usuarios/templates/usuarios/logout.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Logout</title>
{% endblock title_head %}

{% block h1_header  %}
        <h1>Te deslogueaste con exito!</h1>
{% endblock h1_header %}

usuarios/templates/usuarios/registro.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Registro</title>
{% endblock title_head %}

{% block h1_header  %}
<h1 class="mb-5"> Registro</h1>
{% endblock h1_header %}

{% block contenido %}

{% if formulario.errors %}
<p style="color: red">Hay errores</p>
{% endif %}

<form action={% url 'usuarios:registro' %} method="post">
    {% csrf_token %}
    <table>
    {{formulario}}
    </table>
    <button> Registrarse </button>
</form>
{% endblock contenido %}